### ISSUE TITLE
Using S3 for custom storage 

### ISSUE THREAD

**Issue by errorstudent** [Api2Pdf/api2pdf.node#14] opened 2023-02-28 13:56 UTC
I tried to convert html to pdf by enabling the custom storage to S3, but I got this error:

```
 SyntaxError: Unexpected token F in JSON at position 9
     at JSON.parse (<anonymous>)
     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/api2pdf/index.js:205:25)
     at IncomingMessage.emit (node:events:525:35)
     at IncomingMessage.emit (node:domain:489:12)
     at endReadableNT (node:internal/streams/readable:1359:12)
     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Any idea to solve this one?

**Comment by apexdodge** [comment] 2023-02-28 14:05
Are you able to get it working outside of the node.js package. 

Validate that your API call itself is correct by testing it in PostMan or other tool, or use the swagger docs to test it out: https://www.api2pdf.com/how-to-use-api2pdfs-swaggerhub-to-get-the-most-out-of-our-support-team/

**Comment by errorstudent** [comment] 2023-03-01 03:37
it's also not working

```
{
  "ResponseId": "261f07e3-76f0-43ce-9e39-5d2d1650ab38",
  "MbOut": 0,
  "Cost": 0.000204011,
  "Seconds": 1,
  "Error": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>*******</AWSAccessKeyId><StringToSign>**********</Error>",
  "Success": false,
  "FileUrl": null
}
```

this is the body payload
```
{
  "html": "<p>Hello World</p>",
  "inline": true,
  "fileName": "test.pdf",
  "options": {
    "orientation": "Portrait",
    "pageSize": "A4"
  },
  "enableToc": false,
  "tocOptions": {
    "tocHeaderText": "Lorem Ipsum",
    "tocLevelIndentation": "1em"
  },
  "useCustomStorage": true,
  "storage": {
    "method": "PUT",
    "url": "https://*****",
  }
}
```

is there something I missed?

**Comment by errorstudent** [comment] 2023-03-01 03:38
it's also not working

```
{
  "ResponseId": "261f07e3-76f0-43ce-9e39-5d2d1650ab38",
  "MbOut": 0,
  "Cost": 0.000204011,
  "Seconds": 1,
  "Error": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>*******</AWSAccessKeyId><StringToSign>**********</Error>",
  "Success": false,
  "FileUrl": null
}
```

this is the body payload
```
{
  "html": "<p>Hello World</p>",
  "inline": true,
  "fileName": "test.pdf",
  "options": {
    "orientation": "Portrait",
    "pageSize": "A4"
  },
  "enableToc": false,
  "tocOptions": {
    "tocHeaderText": "Lorem Ipsum",
    "tocLevelIndentation": "1em"
  },
  "useCustomStorage": true,
  "storage": {
    "method": "PUT",
    "url": "https://*****",
  }
}
```

is there something I missed?

**Comment by apexdodge** [comment] 2023-03-01 13:01
That error message in the response:

`<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>*******</AWSAccessKeyId><StringToSign>**********</Error>`

This means you have an issue generating a presigned url for aws s3 correctly. You should resolve that separately as it has nothing to do with api2pdf, but it is likely the cause of why it is crashing because it's failing to upload to your s3 url.

Closing as unrelated.

Thanks

**Closed as completed by apexdodge** 2023-03-01 13:01 UTC
Labels: invalid
